config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders, only: [:index, :update, :destroy, :show] do
      get 'eager', on: :collection
    end
  end

  post    '/orders'                =>  'admin/orders#create'
  get     '/admin/menu_items'      =>  'menu_items#man_index'
  get     '/admin'                 =>  'menu_items#man_index'
  get     '/admin/menu_items/new'  =>  'menu_items#new'
  put     '/admin/menu_items/:id'  =>  'menu_items#update'
  post    '/admin/menu_items'      =>  'menu_items#create'
  delete  '/admin/menu_items/:id'  =>  'menu_items#destroy'

  get     '/yipinyao'              =>  'yipinyao#auth'
  post    '/yipinyao'              =>  'yipinyao#service'

  devise_for :users

  root 'menu_items#index'
  resources :menu_items, only: [:index]

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  def to_line_item(count)
    LineItem.new(label: label, price: price, number: count)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  scope :today, -> { where("created_at >= ?", Time.now.beginning_of_day) }

  PASSWORD = '123456'

  ST_NEW = 0
  ST_OVER = 1
  ST_OBSOLETE= 2
  ST_HUMAN_MAP = {ST_NEW => '未完成', ST_OVER => '已完成', ST_OBSOLETE => '废弃'}

  class << self
    def create_order(contact, orders)
      order = Order.new({status: ST_NEW}.merge(contact))

      menu_items = MenuItem.find(orders.keys());
      menu_items.each do |item|
        id = item.id
        count = orders[id.to_s]
        order.line_items << item.to_line_item(count)
      end
      order.save!
      order
    end
  end

  def status_human
    ST_HUMAN_MAP[status]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  skip_before_action :authenticate_user!, only: [:create]

  def index
    if params[:all]
      @orders = Order.order(created_at: :desc, updated_at: :desc)
    else
      @orders = Order.includes(:line_items).today.order(created_at: :desc, updated_at: :desc)
    end
  end

  def eager
    @orders = Order.includes(:line_items).today.where(status: Order::ST_NEW).order(created_at: :asc)
  end

  def create
    contact = params[:contact]
    orders = params[:orders]
    order = Order.create_order(contact, orders)
    render json: order, status: :created
  end

  def update
    order = Order.find(params[:id])
    order.update_attributes!(order_params)
    render json: order, status: :ok
  end

  def show
    @order = Order.find(params[:id])
    @line_items = @order.line_items
    @total_price = @line_items.inject(0) { |memo, el| memo + el.price }
  end

  def destroy
  end

  private

  def order_params
    params.require(:order).permit(:status, :ship_address, :realname, :weixin_openid, :tel)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :store_location
  protect_from_forgery with: :exception

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  protected

  def after_sign_in_path_for(resource)
    session[:previous_url] || admin_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < Admin::AdminController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  def index
    @menu_items = MenuItem.where(enabled: true).order(:created_at, :desc)
  end

  def man_index
    @menu_items = MenuItem.order(:created_at, :desc)
  end

  def show
  end

  def edit
  end

  def create
    _menu_item_params = params.permit(:label, :price, :desc)
    preview_data = params[:preview].read()
    preview_url = "previews/#{Time.now.to_i}.jpg"
    File.open("public/" + preview_url, "wb") { |f| f.write(preview_data) }
    _menu_item_params = {preview_url: preview_url, enabled: true}.merge(_menu_item_params)
    item = MenuItem.new(_menu_item_params)
    item.save()
    redirect_to admin_menu_items_path
  end

  def update
    @menu_item.update(menu_item_params)
    render json: @menu_item, status: :ok
  end

  def destroy
    @menu_item.destroy
    render json: true, status: :ok
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def menu_item_params
    params.require(:menu_item).permit(:label, :price, :enabled, :preview_url, :desc)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    if params[:today]
      @orders = Order.includes(:line_item).today.order(:created_at, :desc)
    else
      @orders = Order.order(:created_at, :desc)
    end
  end

  def create
    contact = params[:contact]
    orders = params[:orders]
    order = Order.create_order(contact, orders)
    render json: order, status: :created
  end

  def destroy
  end
end

app/controllers/yipinyao_controller.rb
class YipinyaoController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :check_signature
  TOKEN = 'ysiupninnyypaeongfeigls0902'

  def auth
    echostr = params[:echostr]
    render text: echostr, status: :ok
  end

  def service
    data = params[:xml]
    if data[:MsgType] == "text"
      page = (data[:Content] == '菜' || data[:Content] == 'cai') ? :yipinyao : :fun
      render page, formats: :xml
    else
      head :forbidden
    end
  end

  private

  def check_signature
    signature = params[:signature]
    timestamp = params[:timestamp]
    nonce = params[:nonce]
    tmp_str = [TOKEN, timestamp, nonce].sort!.join
    tmp_str = Digest::SHA1.hexdigest(tmp_str)
    render text: "Forbidden", status: :forbidden if tmp_str != signature
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def elapsed(order_at)
    secs = Time.now.getlocal - order_at.getlocal
    hours = (secs / 3600).floor
    minutes = ((secs - hours * 3600) / 60).floor

    if hours > 0
      elapse_time = "<span style='color:red'>#{hours}时#{minutes}分钟</span>"
    elsif hours > 24
      elapse_time = "大于一天"
    else
      elapse_time = "#{minutes}分钟"
    end

    elapse_time
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
  def action_label(item)
    item.enabled ? '下架' : '上架'
  end
end

app/views/admin/orders/_line_item.html.erb
<div class="col-md-4 col-xs-12 o-order-item">
  <div class="o-item-count"><span><%= line_item.number %>*</span></div>
  <%= line_item.label %>
</div>

app/views/admin/orders/destroy.html.erb
<h1>Admin::Orders#destroy</h1>
<p>Find me in app/views/admin/orders/destroy.html.erb</p>

app/views/admin/orders/eager.html.erb
<% content_for :head do %>
    <%= javascript_include_tag params[:controller] %>
    <%= stylesheet_link_tag params[:controller] %>
<% end %>

<% content_for :nav_links do %>
    <li><a href="/admin/orders">今日订单</a></li>
    <li class="active"><a href="/admin/orders/eager">未处理订单</a></li>
<% end %>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>姓名</th>
      <th>手机</th>
      <th>下单时间</th>
      <th>已过去</th>
      <th class="o-op-col">#</th>
    </tr>
    </thead>
    <tbody id="i-all-orders">
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.realname %></td>
          <td><%= order.tel %></td>
          <td><%= order.created_at.getlocal.strftime('%H:%M') %></td>
          <td><%= elapsed(order.created_at).html_safe %></td>
          <td class="o-op-col"><input type="hidden" value="<%= order.id %>"></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag params[:controller] %>
  <%= stylesheet_link_tag params[:controller] %>
<% end %>

<% content_for :nav_links do %>
  <li class="active"><a href="#">今日订单</a></li>
  <li><a href="/admin/orders/eager">未处理订单</a></li>
<% end %>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>姓名</th>
      <th>手机</th>
      <th>下单时间</th>
      <th>标签</th>
      <th class="o-op-col">#</th>
    </tr>
    </thead>
    <tbody id="i-all-orders">
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.realname %></td>
        <td><%= order.tel %></td>
        <td><%= order.created_at.getlocal.strftime('%H:%M') %></td>
        <td><%= order.status_human %></td>
        <td class="o-op-col"><input type="hidden" value="<%= order.id %>"></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag (params[:controller] + "_show") %>
  <%= stylesheet_link_tag (params[:controller] + "_show") %>
<% end %>

<% content_for :nav_links do %>
  <li class="active"><a href="#">订单详情</a></li>
  <li><a href="/admin/orders">今日订单</a></li>
<% end %>

<div class="container">
  <table class="table">
    <tr>
      <td colspan="2">
        <span class="pull-right">
          <a href="javascript:void(0)" id="i-action-finish" class="action-link">完成</a>
          <a href="javascript:void(0)" id="i-action-new" class="action-link">未完成</a>
          <input type="hidden" id="i-order-id" value="<%= @order.id %>">
        </span>
      </td>
    </tr>
    <tr>
      <td>顾客姓名</td>
      <td><%= @order.realname %></td>
    </tr>
    <tr>
      <td>联系电话</td>
      <td><%= @order.tel %></td>
    </tr>
    <tr>
      <td>订单时间</td>
      <td><%= @order.created_at.getlocal.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
    <tr>
      <td>送餐地点</td>
      <td><%= @order.ship_address %></td>
    </tr>
  </table>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>订单内容</th>
      <th>价格</th>
    </tr>
    </thead>
    <tbody>
    <% @line_items.each do |item| %>
      <tr>
        <td><%= item.label %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
    <td colspan="2">共计：<%= @total_price %>￥</td>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="description" content="美食工坊">
  <meta name="author" content="gaols jipf">

  <title>美食工坊</title>

  <!-- Bootstrap core CSS -->
  <link href="http://cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :head %>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <!--<script src="js/ie10-viewport-bug-workaround.js"></script>-->
  <!--<link href="css/dms.css" rel="stylesheet">-->
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--&lt;!&ndash;[if lt IE 9]>-->
  <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>-->
  <!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
  <!--<![endif]&ndash;&gt;-->
  <%= csrf_meta_tags %>
</head>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">dms</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= yield :nav_links %>
        <% if user_signed_in? %>
            <li>
              <%= link_to('注销', destroy_user_session_path, :method => :delete) %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<!-- nav -->

<%= yield %>

<!-- Placed at the end of the document so the pages load faster -->
<script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for(@menu_item) do |f| %>
  <% if @menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% @menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.text_field :enabled %>
  </div>
  <div class="field">
    <%= f.label :preview_url %><br>
    <%= f.text_field :preview_url %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<div class="col-xs-12 col-md-6 f-menu-item">
  <input type="hidden" value="<%= menu_item.id %>">
  <div class="f-preview-container">
    <img class="f-preview" src="<%= menu_item.preview_url %>">
    <div class="f-mask">
      <div class="f-preview-mask">
      </div>
      <div class="f-item-checked">
        <div class="glyphicon glyphicon-ok"></div>
      </div>
    </div>
  </div>
  <div class="f-details">
    <div>
      <h3 class="f-label"><%= menu_item.label %></h3>
      <p>￥<span class="f-price"><%= menu_item.price %></span><a class="f-link-details" href="javascript:void(0)">详情</a></p>
    </div>
  </div>
</div>

app/views/menu_items/edit.html.erb
<h1>Editing menu_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag params[:controller] %>
  <%= stylesheet_link_tag params[:controller] %>
<% end %>

<% content_for :nav_links do %>
  <li class="active"><a href="#">美食工坊</a></li>
  <li><a href="#about">关于我们</a></li>
  <li><a href="#contact">联系方式</a></li>
<% end %>

<div class="container f-menu-container">
  <div class="row">
    <% @menu_items.each_slice(2) do |slice| %>
      <%= render partial: "menu_item", collection: slice %>
    <% end %>
  </div>
</div>

<!-- all available fast food -->
<div class="navbar navbar-fixed-top f-navbar-top" id="i-navtop-order" role="navigation">
  <div class="container f-nav-links">
    <span>已购：</span><span id="i-order-count">0</span> 份，共￥<span id="i-total-price">0</span>
    <a href="javascript:void(0)" id="i-order-confirm">确定</a>
  </div>
</div>

<div class="navbar navbar-fixed-top f-navbar-top" id="i-navtop-checkout" role="navigation">
  <div class="container f-nav-links">
    <span class="glyphicon glyphicon-chevron-left" id="i-back-order"></span><span> <span style="padding-right:10px">我的购物车</span></span>
    共￥<span id="i-checkout-price">0</span>
    <a href="javascript:void(0)" id="i-order-checkout">下单</a>
  </div>
</div>

<div class="container f-cart-items">
  <div class="checkout">
    <table class="table table-striped table-hover f-checkout-cart">
      <thead>
      <th>餐品</th>
      <th>单价</th>
      <th>#</th>
      </thead>
      <tbody id="cart-items">
      </tbody>
    </table>

    <div class="checkout-section">
      <h3>配送地址</h3>
    </div>
    <%= form_tag('/orders', method: 'post', id: 'i-order-form') do %>
      <div class="form-group">
        <label for="i-tel">联系电话<span class="f-mark-required">*</span></label>
        <input type="text" class="form-control" id="i-tel" placeholder="TEL">
      </div>
      <div class="form-group">
        <label for="i-customer">联系人<span class="f-mark-required">*</span></label>
        <input type="text" class="form-control" id="i-customer" placeholder="张先生/女士">
      </div>
      <div class="form-group">
        <label for="i-ship-address">配送至<span class="f-mark-required">*</span></label>
        <input type="text" class="form-control" id="i-ship-address" placeholder="深圳">
      </div>
    <% end %>
  </div>
</div>

app/views/menu_items/man_index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "admin/#{params[:controller]}_man" %>
  <%= stylesheet_link_tag "admin/#{params[:controller]}_man" %>
<% end %>

<% content_for :nav_links do %>
  <li class="active"><a href="#">全部菜品</a></li>
  <li><a href="/admin/menu_items/new">添加菜品</a></li>
  <li><a href="/admin/orders">今日订单</a></li>
<% end %>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>菜品名</th>
      <th>价格</th>
      <th colspan="2" class="o-op-col">#</th>
    </tr>
    </thead>
    <tbody id="i-all-orders">
    <% @menu_items.each do |item| %>
      <% if item.enabled %>
        <tr>
      <% else %>
        <tr class="disabled-item">
      <% end %>
      <td><%= item.label %></td>
      <td><%= item.price %></td>
      <td>
        <a href="javascript:void(0)" class="o-action-link o-action-toggle-enable"><%= action_label(item) %></a>
        <a href="javascript:void(0)" class="o-action-link o-action-edit">编辑</a>
        <a href="javascript:void(0)" class="o-action-link o-action-del">删除</a>
      </td>
      <td><input class="o-id" type="hidden" value="<%= item.id %>"></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/menu_items/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "admin/#{params[:controller]}_new" %>
  <%= stylesheet_link_tag "admin/#{params[:controller]}_new" %>
<% end %>

<% content_for :nav_links do %>
  <li class="active"><a href="/admin/menu_items/new">菜品添加</a></li>
  <li><a href="/admin">菜品管理</a></li>
<% end %>

<div class="container">
  <%= form_tag('/admin/menu_items', method: 'post', id: 'i-menu-item-new-form', enctype: "multipart/form-data") do %>
    <div class="form-group">
      <label for="i-menu-label">菜品名称<span class="f-mark-required">*</span></label>
      <input type="text" name="label" class="form-control" id="i-menu-label">
    </div>
    <div class="form-group">
      <label for="i-item-price">菜品价格<span class="f-mark-required">*</span></label>
      <input type="text" name="price" class="form-control" id="i-item-price">
    </div>
    <div class="form-group">
      <label for="i-item-preview">菜品预览<span class="f-mark-required">*</span></label>
      <input type="file" name="preview" class="form-control" id="i-item-preview">
    </div>
    <div class="form-group">
      <button type="button" class="btn btn-success" id="i-btn-new-menu-item">上架</button>
    </div>
  <% end %>
</div>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @menu_item.label %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu_item.price %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @menu_item.enabled %>
</p>

<p>
  <strong>Preview url:</strong>
  <%= @menu_item.preview_url %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @menu_item.desc %>
</p>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>

app/views/yipinyao/fun.xml.erb
<xml>
<ToUserName><![CDATA[<%= params[:xml][:FromUserName] %>]]></ToUserName>
<FromUserName><![CDATA[<%= params[:xml][:ToUserName] %>]]></FromUserName>
<CreateTime><%= Time.now.to_i %></CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[http://203.195.140.131]]></Content>
</xml>

app/views/yipinyao/yipinyao.xml.erb
<xml>
<ToUserName><![CDATA[<%= params[:xml][:FromUserName] %>]]></ToUserName>
<FromUserName><![CDATA[<%= params[:xml][:ToUserName] %>]]></FromUserName>
<CreateTime><%= Time.now.to_i %></CreateTime>
<MsgType><![CDATA[news]]></MsgType>
<ArticleCount>1</ArticleCount>
<Articles>
<item>
<Title><![CDATA[欢迎来到一品肴]]></Title>
<Description><![CDATA[亲，点击订餐啦~]]></Description>
<Url><![CDATA[http://203.195.140.131]]></Url>
</item>
</Articles>
</xml>